### ISSUE TITLE
etcd be smart enough to generate the initial cluster env variable on startup

### ISSUE THREAD

**Issue by alaypatel07** [openshift/etcd#23]
When scaling up, the etcd member needs 2 configuration parameters:

- initial cluster state: for scale up the value is `existing`
- initial cluster members: the value is existing members + the new member in the form of `<member-name>=<member-peer-url>`

We should be able to pass client URLs of existing clusters members and have the etcd binary do the following:

1. wait for the member to be added as an `unstarted` member by querying the existing cluster's members.
2. as soon as the member is added, generate the list of initial cluster env variable by querying the existing cluster's members.
3. start etcd with this list

We can add 2 flags:
1. discover-initial-cluster: a boolean if true, the above steps will be executed
2. cluster-client-urls: comma-separated list of client URLs

Things to consider:

1. Etcd should only generate the initial cluster env variable when unstarted. If it boots from already existing state file, i.e. restart, env generation should be skipped.
2. What would be an appropriate polling timeout? start out with 5 mins timeout and 2 seconds retry interval? (possibly add two more configuration parameters)
3. How to justify removing 2 parameters and adding 2 more (possibly 4)?

**Comment by hexfusion** [comment]
etcd itself consumes ENV variables, it does not create them right? Are you speaking about etcd server?

**Comment by hexfusion** [comment]
etcdctl already knows how to generate initial-cluster[1]. Seems you can use this logic[2] in the workflow to solve this problem.

[1] https://github.com/etcd-io/etcd/tree/master/etcdctl#example-6
[2] https://github.com/etcd-io/etcd/blob/master/etcdctl/ctlv3/command/member_command.go#L119
